### PR TITLE
Add adr-tools to deployed Brew packages

### PR DESCRIPTION
**Pull request by grrywlsn**
Allow easier generation of the Architectural Decision Records.

### CODE REVIEW

**Comment by stefano-sequence** [comment]
Nice! I'd approve, but it doesn't look like I can?

**Comment by grrywlsn** [comment]
@stefano-sequence  do you have approval permissions now?

**Comment by stefano-sequence** [comment]
Still no

**Review by stefano-sequence — APPROVED** [review]

**Comment by stefano-sequence** [comment]
Never mind, I actually did, ignore me

**Comment by grrywlsn** [comment]
Thanks @stefano-sequence  💪

**Pull request merged**
